export const ADMIN_LOCALE = "ru-RU";

export const adminRu = {
  common: {
    save: "Сохранить",
    saving: "Сохраняем…",
    discard: "Отменить",
    unsavedChanges: "Есть несохранённые изменения",
    noUnsavedChanges: "Нет несохранённых изменений",
    dashboardHint: "Выберите раздел слева для редактирования контента.",
    settingsHint: "Экспорт, импорт и сброс применяются сразу.",
    delete: "Удалить",
    add: "Добавить",
    saveFailed: "Не удалось сохранить.",
    connectingSupabase: "Проверяем сессию CRM…",
    syncError: "Ошибка синхронизации",
    loadingContent: "Загрузка контента из Supabase…",
    contentSynced: "Контент сайта синхронизируется с Supabase",
    lastUpdate: "последнее обновление",
    label: "Метка",
    title: "Заголовок",
    description: "Описание",
    text: "Текст",
    imageUrl: "Фото (URL)",
    texts: "Тексты",
    name: "Название",
    step: "Шаг",
    card: "Карточка",
    slide: "Слайд",
    question: "Вопрос",
    answer: "Ответ",
    value: "Значение",
    prefix: "Префикс",
    suffix: "Суффикс",
    category: "Категория",
    brand: "Бренд",
    tagline: "Слоган",
    initials: "Инициалы",
    accent: "Акцент (0–5)",
    rating: "Оценка",
    reviewContent: "Текст отзыва",
    author: "Имя / автор",
    review: "Отзыв",
    person: "Сотрудник",
    bio: "Биография",
    role: "Роль",
    specialties: "Специализации (через запятую)",
    language: "Язык",
    sectionLabel: "Метка секции",
    iconId: "ID иконки",
    street: "Улица",
    city: "Город / индекс",
    phoneLink: "Телефон (tel-ссылка)",
    phoneDisplay: "Телефон (отображаемый)",
    email: "Email",
    booksyLink: "Ссылка Booksy",
    lat: "Широта (lat)",
    lng: "Долгота (lng)",
    mapsLink: "Ссылка Google Maps",
    metro: "Метро / как добраться",
    location: "Локация (под текстом)",
    sectionImage: "Фото секции (URL)",
    discount: "Скидка (%)",
    duration: "Длительность (мин)",
    prices: "Цены (PLN)",
    slug: "Slug",
    altKey: "Alt key",
    photoUrl: "URL фото",
    link: "Ссылка",
    date: "Дата",
  },
  home: {
    description: "Hero-слайды и блок новостей на главной странице (до 5 каждого).",
    heroTab: "Hero-слайды",
    newsTab: "Новости",
    heroLimit: (max) => `До ${max} слайдов в карусели на главной.`,
    newsLimit: (max) => `До ${max} новостей. Неактивные скрыты на сайте.`,
    addNews: "Добавить новость",
    newsItem: "Новость",
    newsSectionLabel: "Заголовок секции новостей",
    newsDate: "Дата публикации",
    newsLink: "Ссылка (необязательно)",
    newsLinkLabel: "Текст ссылки",
    activeOnSite: "Показывать на сайте",
  },
  analytics: {
    description: "Google Analytics 4: ID счётчика, включение и отслеживание переходов SPA.",
    enabled: "Аналитика включена",
    consentHint: "События отправляются только после согласия пользователя в cookie-баннере (GDPR).",
    measurementId: "Measurement ID (GA4)",
    measurementHint: "Формат G-XXXXXXXXXX. По умолчанию G-NYM3P4FJJE.",
    trackedTitle: "Что отслеживается",
    trackPageViews: "Просмотры страниц и маршрутов SPA",
    trackConsent: "Принятие / отказ от cookies",
    trackSpa: "Переходы между страницами услуг и каталогом",
  },
  nav: {
    panel: "Панель",
    home: "Главная",
    services: "Услуги",
    cosmetics: "Косметика",
    about: "Философия",
    trust: "Доверие",
    stats: "Статистика",
    team: "Команда",
    reviews: "Отзывы",
    gallery: "Галерея",
    faq: "FAQ",
    contact: "Контакты",
    analytics: "Аналитика",
    settings: "Настройки",
    groupContent: "Контент",
    groupSite: "Сайт",
    groupSystem: "Система",
    viewSite: "Открыть сайт",
    logout: "Выйти",
    adminTitle: "Админ-панель",
    localOnly: "Только локально",
  },
  auth: {
    login: "Вход",
    loginFailed: "Не удалось войти.",
    enterPanel: "Войти в панель",
    loggingIn: "Вход…",
    supabaseHint: "Тот же email и пароль, что в CRM — или откройте админку кнопкой «Открыть админку» в разделе Сайт.",
    crmSsoHint: "При входе из CRM пароль не нужен — откроется автоматически.",
    localHint: "Локальная панель — изменения сохраняются в браузере.",
    password: "Пароль",
    emailRequired: "Укажите email и пароль Supabase.",
    wrongPassword: "Неверный пароль.",
    supabaseNotConfigured:
      "Вход из CRM не сработал: на сайте не подключён Supabase. Пересоберите деплой с VITE_SUPABASE_URL и ключом.",
    ssoFailed: "Не удалось принять сессию из CRM. Откройте админку снова из раздела «Сайт» в CRM.",
  },
  crm: {
    noServices: "В CRM нет услуг для синхронизации.",
    supabaseNotConfigured: "Supabase не настроен.",
    loginSameAccount: "Войдите тем же аккаунтом, что в CRM.",
    noCrmData: "Нет данных CRM в Supabase. Откройте CRM, войдите и дождитесь сохранения.",
    syncFailed: "Синхронизация с CRM не удалась.",
    importFromCrm: "Импорт цен из CRM",
    importing: "Импорт из CRM…",
    imported: (matched, total) =>
      `Импортировано и сохранено на сайте (${matched}/${total} услуг). Описания и фото без изменений.`,
  },
  sync: {
    fetchFailed: "Не удалось загрузить контент из Supabase.",
    saveFailed: "Не удалось сохранить в Supabase.",
    clearFailed: "Не удалось очистить Supabase.",
    publishFull: "Опубликовать все данные в Supabase",
    publishing: "Публикация…",
    publishDone: "Все данные сохранены в Supabase. Изображения — в таблице site_images.",
    publishConfirm:
      "Сохранить полный снимок сайта (услуги, тексты, отзывы, галерея, FAQ) в Supabase? Текущие данные в базе будут заменены.",
  },
  media: {
    upload: "Загрузить в базу",
    removeImage: "Удалить фото",
    removeFailed: "Не удалось удалить изображение из базы.",
    uploading: "Загрузка…",
    uploadFailed: "Не удалось загрузить изображение.",
    storageNotConfigured: "Таблица site_images не настроена. Запустите миграцию 003_site_images.sql.",
    invalidFileType: "Допустимы только изображения: JPG, PNG, WebP, GIF, SVG.",
    fileTooLarge: "Файл больше 5 МБ.",
    storedInDb: "В базе",
    legacyUrlHint: "Старая ссылка — загрузите файл, чтобы сохранить в базе.",
    noImage: "Изображение не выбрано.",
    storageHint:
      "Изображения хранятся в таблице site_images. Запустите SQL из supabase/migrations/003_site_images.sql.",
    replacedDeleted: "Старое фото удалено из базы.",
    storageUsage: (usedMb, count, limitMb = 50) =>
      `Хранилище: ${usedMb} МБ / ~${limitMb} МБ · ${count} файлов`,
    cleanupOrphans: "Очистить неиспользуемые фото",
    cleanupDone: (count) =>
      count > 0 ? `Удалено неиспользуемых фото: ${count}.` : "Неиспользуемых фото не найдено.",
    cleanupFailed: "Не удалось очистить хранилище.",
  },
};
