export const ADMIN_LOCALE = "ru-RU";

export const adminRu = {
  common: {
    save: "Сохранить",
    saving: "Сохраняем…",
    discard: "Отменить",
    unsavedChanges: "Есть несохранённые изменения",
    unsavedChangesBanner: "Несохранённые изменения — сохраните или отмените перед уходом со страницы.",
    leaveUnsaved: "Есть несохранённые изменения. Уйти без сохранения?",
    noUnsavedChanges: "Нет несохранённых изменений",
    saveSuccess: "Изменения сохранены на сайте.",
    saveShortcut: "⌘S / Ctrl+S — сохранить",
    commandSearch: "Перейти в раздел…",
    commandEmpty: "Раздел не найден",
    commandHint: "⌘K / Ctrl+K — быстрый переход · Esc — закрыть",
    commandPalette: "Быстрый переход",
    searchList: "Поиск в списке…",
    viewSection: "На сайте",
    confirmDeleteTitle: "Удалить?",
    confirmDeleteMessage: "Элемент будет удалён из черновика. Не забудьте сохранить изменения.",
    syncHealthy: "Синхронизация в норме",
    syncErrorShort: "Ошибка синхронизации",
    openSettings: "Настройки",
    draftRecoveryHint: "Найден несохранённый черновик этой страницы.",
    draftRestore: "Восстановить",
    draftDismiss: "Удалить черновик",
    emptyList: "Список пуст — добавьте первый элемент.",
    searchNoResults: "Ничего не найдено по запросу.",
    clone: "Дублировать",
    lastEdited: "Последнее сохранение",
    neverEdited: "ещё не сохранялось",
    charCount: (current, max) => `${current} / ${max}`,
    dashboardHint: "Выберите раздел слева для редактирования контента.",
    settingsHint: "Экспорт, импорт и сброс применяются сразу.",
    delete: "Удалить",
    add: "Добавить",
    confirm: "Подтвердить",
    cancel: "Отмена",
    saveFailed: "Не удалось сохранить.",
    connectingSupabase: "Проверяем сессию CRM…",
    syncError: "Ошибка синхронизации",
    loadingContent: "Загрузка контента из Supabase…",
    contentSynced: "Контент сайта синхронизируется с Supabase",
    lastUpdate: "последнее обновление",
    label: "Метка",
    title: "Заголовок",
    description: "Описание",
    text: "Текст",
    imageUrl: "Фото (URL)",
    texts: "Тексты",
    name: "Название",
    step: "Шаг",
    card: "Карточка",
    slide: "Слайд",
    question: "Вопрос",
    answer: "Ответ",
    value: "Значение",
    prefix: "Префикс",
    suffix: "Суффикс",
    category: "Категория",
    brand: "Бренд",
    tagline: "Слоган",
    initials: "Инициалы",
    accent: "Акцент (0–5)",
    rating: "Оценка",
    reviewContent: "Текст отзыва",
    author: "Имя / автор",
    review: "Отзыв",
    person: "Сотрудник",
    bio: "Биография",
    role: "Роль",
    specialties: "Специализации (через запятую)",
    language: "Язык",
    sectionLabel: "Метка секции",
    iconId: "ID иконки",
    street: "Улица",
    city: "Город / индекс",
    phoneLink: "Телефон (tel-ссылка)",
    phoneDisplay: "Телефон (отображаемый)",
    email: "Email",
    booksyLink: "Ссылка Booksy",
    lat: "Широта (lat)",
    lng: "Долгота (lng)",
    mapsLink: "Ссылка Google Maps",
    metro: "Метро / как добраться",
    location: "Локация (под текстом)",
    sectionImage: "Фото секции (URL)",
    discount: "Скидка (%)",
    duration: "Длительность (мин)",
    prices: "Цены (PLN)",
    slug: "Slug",
    altKey: "Alt key",
    photoUrl: "URL фото",
    link: "Ссылка",
    date: "Дата",
  },
  cosmetics: {
    description:
      "Поля как на сайте: фото, категории (можно несколько), популярность (до 3 на главной), название, объём, описание и состав. ID — случайный номер, закрепляется за товаром. Название не переводится — пишите его в нужном языке. Объём только в ml или g.",
    authoringHint:
      "Пишите на русском во вкладке RU. Название товара сохраняется как есть на всех языках. Описание, объём и состав переводятся в PL, EN и UA.",
    previewHint:
      "Просмотр автоперевода для выбранного языка сайта. Редактирование — только во вкладке RU.",
    statusTranslating: "Переводим на PL, EN и UA…",
    addProduct: "Добавить продукт",
    newProduct: "Новый продукт",
    productId: "Номер товара",
    photo: "Фото",
    transparentPhoto: "Фото без фона (PNG)",
    transparentPhotoOn: "Светлая подложка под прозрачное фото",
    transparentPhotoOff: "Тёмная подложка — у фото уже есть свой фон",
    cardSection: "Карточка на сайте",
    siteTexts: "Тексты на сайте",
    category: "Категории",
    featured: "Популярный на главной",
    featuredOn: "Показывается в ленте (до 3)",
    featuredOff: "Не в ленте",
    featuredLimit: (max) => `На главной можно выбрать не больше ${max} товаров.`,
    idPickerTitle: "Выберите номер для нового товара",
    idPickerHint: "Этот товар раньше был в каталоге. Можно вернуть старый номер или сгенерировать новый.",
    retiredId: "Свободный номер",
    useRetiredId: "Присвоить выбранный",
    generateNewId: "Сгенерировать новый",
    cancelAdd: "Отмена",
    confirmAddTitle: "Добавить товар?",
    confirmAddMessage: "Новая карточка появится сверху списка. Не забудьте сохранить изменения.",
    confirmDeleteTitle: "Удалить товар?",
    confirmDeleteMessage: (name, id) =>
      `Удалить «${name}» (№ ${id})? Фото товара тоже будет удалено.`,
    confirmRetiredIdTitle: "Присвоить старый номер?",
    confirmRetiredIdMessage: (id) => `Новому товару будет присвоен номер ${id}.`,
    confirmNewIdTitle: "Сгенерировать новый номер?",
    confirmNewIdMessage: "Будет создан новый случайный номер товара.",
    statusAdded: "Товар добавлен. Сохраните изменения.",
    statusDeleted: "Товар удалён. Сохраните изменения.",
    statusSaved: "Каталог сохранён на сайте.",
    newProductBadge: "Новый",
    name: "Название",
    productDescription: "Описание",
    volume: "Объём",
    composition: "Состав",
    categories: {
      "candles-aroma": "Свечи и ароматы",
      "pro-cosmetics": "Профессиональная косметика",
      "home-spa": "Домашний SPA",
      "anti-cellulite": "Антицеллюлитный уход",
      "gift-certificates": "Подарочные сертификаты",
      "nuar-premium": "Премиум товары Nuar",
    },
  },
  faq: {
    description: "Пишите вопросы и ответы на русском (вкладка RU). При сохранении автоперевод в PL, EN и UA.",
    authoringHint:
      "Пишите на русском во вкладке RU. При сохранении FAQ автоматически переводится в PL, EN и UA.",
    previewHint: "Просмотр автоперевода. Редактирование — только во вкладке RU.",
    statusTranslating: "Переводим FAQ на PL, EN и UA…",
  },
  home: {
    description: "Hero-слайды и блок новостей на главной странице (до 5 каждого).",
    heroTab: "Hero-слайды",
    newsTab: "Новости",
    heroLimit: (max) => `До ${max} слайдов в карусели на главной.`,
    newsLimit: (max) => `До ${max} новостей. Неактивные скрыты на сайте.`,
    addNews: "Добавить новость",
    newsItem: "Новость",
    newsSectionLabel: "Заголовок секции новостей",
    newsDate: "Дата публикации",
    newsLink: "Ссылка (необязательно)",
    newsLinkLabel: "Текст ссылки",
    activeOnSite: "Показывать на сайте",
  },
  analytics: {
    description: "Google Analytics 4: ID счётчика, включение и отслеживание переходов SPA.",
    enabled: "Аналитика включена",
    consentHint: "События отправляются только после согласия пользователя в cookie-баннере (GDPR).",
    measurementId: "Measurement ID (GA4)",
    measurementHint: "Формат G-XXXXXXXXXX. По умолчанию G-NYM3P4FJJE.",
    trackedTitle: "Что отслеживается",
    trackPageViews: "Просмотры страниц и маршрутов SPA",
    trackConsent: "Принятие / отказ от cookies",
    trackSpa: "Переходы между страницами услуг и каталогом",
  },
  nav: {
    panel: "Панель",
    home: "Главная",
    services: "Услуги",
    cosmetics: "Каталог",
    about: "Философия",
    trust: "Доверие",
    stats: "Статистика",
    team: "Команда",
    reviews: "Отзывы",
    gallery: "Галерея",
    faq: "FAQ",
    contact: "Контакты",
    analytics: "Аналитика",
    settings: "Настройки",
    groupContent: "Контент",
    groupSite: "Сайт",
    groupSystem: "Система",
    viewSite: "Открыть сайт",
    logout: "Выйти",
    adminTitle: "Админ-панель",
    localOnly: "Только локально",
  },
  auth: {
    login: "Вход",
    loginFailed: "Не удалось войти.",
    enterPanel: "Войти в панель",
    loggingIn: "Вход…",
    supabaseHint: "Тот же email и пароль, что в CRM — или откройте админку кнопкой «Открыть админку» в разделе Сайт.",
    crmSsoHint: "При входе из CRM пароль не нужен — откроется автоматически.",
    localHint: "Локальная панель — изменения сохраняются в браузере.",
    password: "Пароль",
    emailRequired: "Укажите email и пароль Supabase.",
    wrongPassword: "Неверный пароль.",
    supabaseNotConfigured:
      "Вход из CRM не сработал: на сайте не подключён Supabase. Пересоберите деплой с VITE_SUPABASE_URL и ключом.",
    ssoFailed: "Не удалось принять сессию из CRM. Откройте админку снова из раздела «Сайт» в CRM.",
  },
  crm: {
    noServices: "В CRM нет услуг для синхронизации.",
    supabaseNotConfigured: "Supabase не настроен.",
    loginSameAccount: "Войдите тем же аккаунтом, что в CRM.",
    noCrmData: "Нет данных CRM в Supabase. Откройте CRM, войдите и дождитесь сохранения.",
    syncFailed: "Синхронизация с CRM не удалась.",
    importFromCrm: "Импорт цен из CRM",
    importing: "Импорт из CRM…",
    imported: (matched, total) =>
      `Импортировано и сохранено на сайте (${matched}/${total} услуг). Описания и фото без изменений.`,
  },
  sync: {
    fetchFailed: "Не удалось загрузить контент из Supabase.",
    saveFailed: "Не удалось сохранить в Supabase.",
    clearFailed: "Не удалось очистить Supabase.",
    publishFull: "Опубликовать все данные в Supabase",
    publishing: "Публикация…",
    publishDone: "Все данные сохранены в Supabase. Изображения — в таблице site_images.",
    publishConfirm:
      "Сохранить полный снимок сайта (услуги, тексты, отзывы, галерея, FAQ) в Supabase? Текущие данные в базе будут заменены.",
  },
  media: {
    upload: "Загрузить в базу",
    removeImage: "Удалить фото",
    removeFailed: "Не удалось удалить изображение из базы.",
    uploading: "Загрузка…",
    uploadFailed: "Не удалось загрузить изображение.",
    storageNotConfigured: "Таблица site_images не настроена. Запустите миграцию 003_site_images.sql.",
    invalidFileType: "Допустимы только изображения: JPG, PNG, WebP, GIF, SVG.",
    fileTooLarge: "Файл больше 5 МБ.",
    storedInDb: "В базе",
    legacyUrlHint: "Старая ссылка — загрузите файл, чтобы сохранить в базе.",
    noImage: "Изображение не выбрано.",
    storageHint:
      "Изображения хранятся в таблице site_images. Запустите SQL из supabase/migrations/003_site_images.sql.",
    replacedDeleted: "Старое фото удалено из базы.",
    storageUsage: (usedMb, count, limitMb = 50) =>
      `Хранилище: ${usedMb} МБ / ~${limitMb} МБ · ${count} файлов`,
    cleanupOrphans: "Очистить неиспользуемые фото",
    cleanupDone: (count) =>
      count > 0 ? `Удалено неиспользуемых фото: ${count}.` : "Неиспользуемых фото не найдено.",
    cleanupFailed: "Не удалось очистить хранилище.",
    pickFromLibrary: "Из библиотеки",
    libraryTitle: "Библиотека изображений",
    libraryEmpty: "В этой папке пока нет загруженных фото.",
    librarySearch: "Поиск по ID…",
  },
  help: {
    altKey: "Ключ подписи к фото. Должен совпадать с переводом gallery.items.* на сайте.",
    transparentPhoto: "Включите для PNG без фона — на сайте будет светлая подложка.",
    crmPrices: "Цены и длительность редактируются в CRM, здесь только просмотр.",
    heroLimit: "На главной показывается не больше 5 слайдов и 5 новостей.",
    featuredCosmetics: "На главной в ленте каталога — максимум 3 товара.",
    productCategories: "Отметьте все категории, где товар должен появляться в фильтре каталога. Минимум одна.",
  },
};
