export const ADMIN_LOCALE = "ru-RU";

export const adminRu = {
  common: {
    save: "Сохранить",
    saving: "Сохраняем…",
    discard: "Отменить",
    unsavedChanges: "Есть несохранённые изменения",
    noUnsavedChanges: "Нет несохранённых изменений",
    dashboardHint: "Выберите раздел слева для редактирования контента.",
    settingsHint: "Экспорт, импорт и сброс применяются сразу.",
    delete: "Удалить",
    add: "Добавить",
    saveFailed: "Не удалось сохранить.",
    connectingSupabase: "Подключение к Supabase…",
    syncError: "Ошибка синхронизации",
    loadingContent: "Загрузка контента из Supabase…",
    contentSynced: "Контент сайта синхронизируется с Supabase",
    lastUpdate: "последнее обновление",
    label: "Метка",
    title: "Заголовок",
    description: "Описание",
    text: "Текст",
    imageUrl: "Фото (URL)",
    texts: "Тексты",
    name: "Название",
    step: "Шаг",
    card: "Карточка",
    slide: "Слайд",
    question: "Вопрос",
    answer: "Ответ",
    value: "Значение",
    prefix: "Префикс",
    suffix: "Суффикс",
    category: "Категория",
    brand: "Бренд",
    tagline: "Слоган",
    initials: "Инициалы",
    accent: "Акцент (0–5)",
    rating: "Оценка",
    reviewContent: "Текст отзыва",
    author: "Имя / автор",
    review: "Отзыв",
    person: "Сотрудник",
    bio: "Биография",
    role: "Роль",
    specialties: "Специализации (через запятую)",
    language: "Язык",
    sectionLabel: "Метка секции",
    iconId: "ID иконки",
    street: "Улица",
    city: "Город / индекс",
    phoneLink: "Телефон (tel-ссылка)",
    phoneDisplay: "Телефон (отображаемый)",
    email: "Email",
    booksyLink: "Ссылка Booksy",
    lat: "Широта (lat)",
    lng: "Долгота (lng)",
    mapsLink: "Ссылка Google Maps",
    metro: "Метро / как добраться",
    location: "Локация (под текстом)",
    sectionImage: "Фото секции (URL)",
    discount: "Скидка (%)",
    duration: "Длительность (мин)",
    prices: "Цены (PLN)",
    slug: "Slug",
    altKey: "Alt key",
    photoUrl: "URL фото",
  },
  nav: {
    panel: "Панель",
    home: "Главная",
    services: "Услуги",
    cosmetics: "Косметика",
    about: "Философия",
    trust: "Доверие",
    stats: "Статистика",
    team: "Команда",
    reviews: "Отзывы",
    gallery: "Галерея",
    faq: "FAQ",
    contact: "Контакты",
    settings: "Настройки",
    viewSite: "Открыть сайт",
    logout: "Выйти",
    adminTitle: "Админ-панель",
    localOnly: "Только локально",
  },
  auth: {
    login: "Вход",
    loginFailed: "Не удалось войти.",
    enterPanel: "Войти в панель",
    loggingIn: "Вход…",
    supabaseHint: "Войдите через Supabase (тот же аккаунт, что в CRM).",
    localHint: "Локальная панель — изменения сохраняются в браузере.",
    password: "Пароль",
    emailRequired: "Укажите email и пароль Supabase.",
    wrongPassword: "Неверный пароль.",
  },
  crm: {
    noServices: "В CRM нет услуг для синхронизации.",
    supabaseNotConfigured: "Supabase не настроен.",
    loginSameAccount: "Войдите тем же аккаунтом, что в CRM.",
    noCrmData: "Нет данных CRM в Supabase. Откройте CRM, войдите и дождитесь сохранения.",
    syncFailed: "Синхронизация с CRM не удалась.",
    importFromCrm: "Импорт цен из CRM",
    importing: "Импорт из CRM…",
    imported: (matched, total) =>
      `Импортировано и сохранено на сайте (${matched}/${total} услуг). Описания и фото без изменений.`,
  },
  sync: {
    fetchFailed: "Не удалось загрузить контент из Supabase.",
    saveFailed: "Не удалось сохранить в Supabase.",
    clearFailed: "Не удалось очистить Supabase.",
    publishFull: "Опубликовать все данные в Supabase",
    publishing: "Публикация…",
    publishDone: "Все данные сохранены в Supabase. Изображения — в таблице site_images.",
    publishConfirm:
      "Сохранить полный снимок сайта (услуги, тексты, отзывы, галерея, FAQ) в Supabase? Текущие данные в базе будут заменены.",
  },
  media: {
    upload: "Загрузить в базу",
    uploading: "Загрузка…",
    uploadFailed: "Не удалось загрузить изображение.",
    storageNotConfigured: "Таблица site_images не настроена. Запустите миграцию 003_site_images.sql.",
    invalidFileType: "Допустимы только изображения: JPG, PNG, WebP, GIF, SVG.",
    fileTooLarge: "Файл больше 5 МБ.",
    storedInDb: "В базе",
    legacyUrlHint: "Старая ссылка — загрузите файл, чтобы сохранить в базе.",
    noImage: "Изображение не выбрано.",
    storageHint:
      "Изображения хранятся в таблице site_images. Запустите SQL из supabase/migrations/003_site_images.sql.",
  },
};
